"""Add status column to payments

Revision ID: 950fe487cd77
Revises: 
Create Date: 2026-03-11 19:25:58.921215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950fe487cd77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('week_start_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('week_start_date')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
